{
 "title": "Pizza Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(REVENUE_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(SOLD_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "FAILED_PIZZAS_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(TOTAL_total{source=\"jwt-pizza-service\"}[1m]) + sum(POST_total{source=\"jwt-pizza-service\"}) + sum(PUT_total) + sum(DELETE_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(GET_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(POST_total[1m])", "legendFormat": "__auto" },
    {
     "expr": "rate(PUT_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(DELETE_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(ACTIVE_USERS_total{source=\"jwt-pizza-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful vs. Failed Authentication",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(SUCCESSFUL_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(FAILED_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "GEN_LATENCY_milliseconds_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "PIZZA_LATENCY_milliseconds_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CPU_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "MEMORY_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}